### ISSUE TITLE
Not able to access/login cluster 

### ISSUE THREAD

**Issue by rfhari** [ArjunaCluster/ArjunaUsers#220]
### Your Name

Hariharan Ramasubramanian

### Andrew ID

hariharr

### Where it Happened

NA

### What Happened?

Hi, I'm not able to access the cluster. I get connection timed out error. Would be great if you can help me out. 

![image](https://user-images.githubusercontent.com/29433819/214684011-8f70b39a-4f16-4225-90e0-bb7df2274af9.png)

**Comment by abillscmu** [comment]
Maybe check internet connection? I'm able to log on

**Comment by rfhari** [comment]
I'm on campus wifi. It is working well otherwise. So I'm not sure if it's an internet problem.

**Comment by abillscmu** [comment]
I am able to log in from an on campus computer, the linux timeshare, and the vpn. I can see that multiple users are currently logged in from the campus wifi network (cmu-secure), and I've been using it from cmu-secure most of the day.

If you're on eduroam I'd suggest trying from cmu-secure, otherwise try the vpn, otherwise try the linux timeshare

relevant docs:
https://arjunacluster.github.io/ArjunaUsers/getting_started/connecting.html
